import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import useSWR from 'swr'

const Home = () => {
  return (
    <main>
      <div className="py-8 bg-slate-100 h-screen w-screen">
        <CentralColumn></CentralColumn>
      </div>
    </main>
  )
}

const GPTTest = () => {
  return <>
    <div className="flex justify-center">
      <div className="w-full md:w-2/3 lg:w-1/2 px-4 py-2">
        <div className="relative">
          <input type="text" className="w-full rounded-lg pl-8 pr-3 py-2 text-gray-700 focus:outline-none focus:shadow-outline" placeholder="Search PCB components" />
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center">
            <svg className="h-6 w-6 fill-current text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path className="heroicon-ui" d="M15.56 14.44A7 7 0 1 1 9.83 9.7a7 7 0 0 1 5.73 4.74zM8 14a6 6 0 1 0 8-5.63V12h2V9.37A8 8 0 1 1 8 14z"></path>
            </svg>
          </div>
        </div>
      </div>
    </div>

    <div className="container mx-auto mt-8">
      <div className="grid grid-cols-1 gap-4">
        <div className="border border-gray-300 rounded-lg shadow-md overflow-hidden">
          <img src="https://via.placeholder.com/400x400" alt="PCB component" className="w-full h-48 object-cover" />
          <div className="p-4">
            <h2 className="text-lg font-semibold text-gray-800">PCB Component Name</h2>
            <p className="text-gray-600 mt-2">Some description of the component.</p>
          </div>
        </div>
      </div>
    </div>

  </>
}

const formatPrice = (price: number) => {
  let level = 2;
  let out = Math.round(price * Math.pow(10, level)) / Math.pow(10, level)

  while (out === 0 && level <= 5) {
    level += 1
    out = Math.round(price * Math.pow(10, level)) / Math.pow(10, level)
  }

  return out
}

function ResistorRow({ image_url, description, manufacturer_id, price, stock }: Part) {
  return (
    <div className="flex items-center bg-white border rounded-lg shadow-md p-4 mb-4 gap-4">
      <div className="">
        <p className="text-gray-600 font-semibold">{manufacturer_id}</p>
      </div>
      <div className="pr-2">
        <img src={`https://assets.lcsc.com/images/lcsc/224x224/${image_url}`} className="w-32 object-contain" ></img>
      </div>
      <div className="">
        <p className="text-gray-600">{description}</p>
      </div>
      <div className="">
        <p className="text-gray-600">${formatPrice(price)}</p>
      </div>
      <div className="">
        <p className="text-gray-600">{stock}</p>
      </div>
    </div>
  );
}


const CentralColumn = () => {
  const [text, setText] = useState<string>("")
  const [results, setResults] = useState<Part[]>([]);

  const debouncedText = useDebounce(text, 300);

  const { data, isLoading, error } = useSWR(`http://localhost:8090/search?q=${debouncedText}`, fetcher)

  useEffect(() => {
    if (data && !isLoading && !error) {
      setResults(data)
    }

  }, [debouncedText, data])

  // console.log(data, isLoading, error)

  return <div className="md:max-w-4xl mx-auto">
    <SearchBox {...{ text, setText }}></SearchBox>
    {results.map((part: Part) => (
      <ResistorRow {...part}></ResistorRow>
    ))}
  </div>
}

// <input type="search" id="default-search" className="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Mockups, Logos..." required

// @ts-ignore
const fetcher = (...args) => fetch(...args).then(x => x.json())

const SearchBox = ({ text, setText }: { text: string, setText: (a0: string) => void }) => {
  return <input value={text} onChange={e => setText(e.target.value)} className="w-full h-8 rounded-lg text-sm p-5 border" placeholder="10k 0603 resistor"></input>
}

interface Part {
  description: string,
  lscs_id: string,
  manufacturer_id: string,
  image_url: string,
  price: number,
  stock: number
}

const Result = (p: Part) => {
  return <div>{p.description}</div>
}

// export default Home

/*
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

*/

function App() {
  const [searchTerm, setSearchTerm] = useState<any>("");
  const [results, setResults] = useState<any>([{ title: 'test', content: 'my description' }, {}, {}]);

  // function to handle search
  function handleSearch(e: any) {
    e.preventDefault();
    // perform search with searchTerm, update results state
  }

  return (
    <div className="bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-semibold text-gray-800 mb-4">Redis Documentation</h1>
        <form onSubmit={handleSearch}>
          <div className="flex items-center max-w-md mb-4">
            <input
              type="text"
              className="w-full bg-white border border-gray-300 rounded py-2 px-4 leading-tight focus:outline-none focus:shadow-outline"
              placeholder="Search Redis Documentation"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <button
              type="submit"
              className="ml-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            >
              Search
            </button>
          </div>
        </form>
        <div className="max-w-md">
          {results.map((result: any) => (
            <div
              key={result.id}
              className="bg-white border border-gray-300 rounded-md shadow-md p-4 mb-4"
            >
              <h2 className="text-lg font-semibold text-gray-800">
                {result.title}
              </h2>
              <p className="text-gray-600 mt-2">{result.content}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Home;

// Hook
// T is a generic type for value parameter, our case this will be string
function useDebounce<T>(value: T, delay: number): T {
  // State and setters for debounced value
  const [debouncedValue, setDebouncedValue] = useState<T>(value);
  useEffect(
    () => {
      // Update debounced value after delay
      const handler = setTimeout(() => {
        setDebouncedValue(value);
      }, delay);
      // Cancel the timeout if value changes (also on delay change or unmount)
      // This is how we prevent debounced value from updating if value is changed ...
      // .. within the delay period. Timeout gets cleared and restarted.
      return () => {
        clearTimeout(handler);
      };
    },
    [value, delay] // Only re-call effect if value or delay changes
  );
  return debouncedValue;
}
